/**
 * Generation pipeline (docs/PHOENIX_SPEC.md §4.3).
 *
 * Input: a finished CapturedStep[] from capture/recorder.js.
 * Output: a named, commented, parameterized script with inferred
 * assertions, saved as a TestOps test case.
 *
 * Runs once, after "Stop" — not live during recording. The model needs
 * the whole flow in view to write a coherent script and propose
 * meaningful assertions, not just react to isolated taps.
 */

/**
 * @param {import('../capture/recorder').CapturedStep[]} steps
 * @returns {Promise<{ scriptSource: string, testName: string, assertions: string[] }>}
 */
async function generateScript(steps) {
  const testName = inferTestName(steps);
  const assertions = inferAssertions(steps);
  const parameters = extractParameters(steps);
  const scriptSource = synthesizeCode(steps, { testName, assertions, parameters });

  return { scriptSource, testName, assertions };
}

/** TODO(stage 2): name the flow from what changed on screen, not a placeholder. */
function inferTestName(steps) {
  return "untitled_recorded_flow";
}

/**
 * Diffs pageSourceBefore/After (and screenshots, for non-accessible UI)
 * per step and proposes assertions from what visibly changed — a new
 * screen appeared, an error message showed up, a value updated.
 * TODO(stage 2): implement the actual diffing + LLM call.
 */
function inferAssertions(steps) {
  return [];
}

/**
 * Flags literal typed values (an email, a search term) so they can be
 * pulled into test data instead of hardcoded.
 * TODO(stage 2): implement.
 */
function extractParameters(steps) {
  return [];
}

/**
 * Turns the resolved step sequence into idiomatic client code: explicit
 * waits instead of hard sleeps, meaningful variable names, step comments.
 * TODO(stage 2): implement — this is the actual LLM code-synthesis call.
 */
function synthesizeCode(steps, meta) {
  return `// Generated by Phoenix — ${meta.testName}\n// ${steps.length} step(s) recorded. Synthesis not yet implemented.\n`;
}

module.exports = { generateScript };
